In [2]:
# Для анализа данных и обработки
import pandas as pd
import numpy as np

# Для визуализации данных
import seaborn as sns
import matplotlib as plt
from matplotlib.ticker import FuncFormatter

%matplotlib inline

# Вопросы исследования и их цели

## 1. Каков общий объем заказов и продаж?
**Цель:** оценить масштаб бизнеса и определить базовые показатели продаж.

---

## 2. Какие размеры пиццы наиболее популярны среди покупателей?
**Цель:** определить потребительские предпочтения для оптимизации ассортимента и управления запасами.

---

## 3. Какие виды пиццы заказывают чаще всего?
**Цель:** выявить наиболее востребованные позиции меню.

---

## 4. Какие категории пиццы наиболее популярны по объему продаж?
**Цель:** определить категории, формирующие основной потребительский спрос.

---

## 5. Как меняется активность заказов в течение дня?
**Цель:** выявить часы пик для оптимизации работы персонала и логистики.

---

## 6. Как распределяется выручка между категориями пиццы?
**Цель:** оценить финансовый вклад каждой категории в общий доход.

---

## 7. Как изменяется количество заказов по дням?
**Цель:** проанализировать дневную динамику продаж и средний объем заказов.

---

## 8. Какие виды пиццы приносят наибольшую выручку?
**Цель:** определить ключевые товары, формирующие основную часть дохода.

---

## 9. Каков вклад каждой категории пиццы в общую выручку?
**Цель:** определить финансовую значимость различных категорий меню.

---

## 10. Как изменяется совокупная выручка во времени?
**Цель:** проанализировать накопительную динамику дохода и выявить тенденции продаж.

---

## 11. Какие виды пиццы являются наиболее доходными внутри каждой категории?
**Цель:** определить лидирующие позиции по выручке в рамках каждой категории пиццы.
---

In [3]:
# таблица о деталях заказа
df_order_details = pd.read_csv('../pizza_hut_da/data/order_details.csv', encoding='windows-1251')
df_order_details.head(10)

   order_details_id  order_id       pizza_id  quantity
0                 1         1     hawaiian_m         1
1                 2         2  classic_dlx_m         1
2                 3         2  five_cheese_l         1
3                 4         2    ital_supr_l         1
4                 5         2     mexicana_m         1
5                 6         2     thai_ckn_l         1
6                 7         3    ital_supr_m         1
7                 8         3   prsc_argla_l         1
8                 9         4    ital_supr_m         1
9                10         5    ital_supr_m         1

In [4]:
# таблица заказов
df_orders = pd.read_csv('../pizza_hut_da/data/orders.csv', encoding='windows-1251')
df_orders.head(10)

   order_id        date      time
0         1  2015-01-01  11:38:36
1         2  2015-01-01  11:57:40
2         3  2015-01-01  12:12:28
3         4  2015-01-01  12:16:31
4         5  2015-01-01  12:21:30
5         6  2015-01-01  12:29:36
6         7  2015-01-01  12:50:37
7         8  2015-01-01  12:51:37
8         9  2015-01-01  12:52:01
9        10  2015-01-01  13:00:15

In [5]:
# таблица типов пиццы
df_pizza_types = pd.read_csv('../pizza_hut_da/data/pizza_types.csv',  encoding='windows-1251', )
df_pizza_types.head(10)

,pizza_type_id,name,category,ingredients
0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,..."
1,cali_ckn,The California Chicken Pizza,Chicken,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ..."
2,ckn_alfredo,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A..."
3,ckn_pesto,The Chicken Pesto Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli..."
4,southw_ckn,The Southwest Chicken Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja..."
5,thai_ckn,The Thai Chicken Pizza,Chicken,"Chicken, Pineapple, Tomatoes, Red Peppers, Tha..."
6,big_meat,The Big Meat Pizza,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau..."
7,classic_dlx,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
8,hawaiian,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"
9,ital_cpcllo,The Italian Capocollo Pizza,Classic,"Capocollo, Red Peppers, Tomatoes, Goat Cheese,..."

In [6]:
# таблица пицц
df_pizzas = pd.read_csv('../pizza_hut_da/data/pizzas.csv', encoding='windows-1251')
df_pizzas.head(10)

        pizza_id pizza_type_id size  price
0      bbq_ckn_s       bbq_ckn    S  12.75
1      bbq_ckn_m       bbq_ckn    M  16.75
2      bbq_ckn_l       bbq_ckn    L  20.75
3     cali_ckn_s      cali_ckn    S  12.75
4     cali_ckn_m      cali_ckn    M  16.75
5     cali_ckn_l      cali_ckn    L  20.75
6  ckn_alfredo_s   ckn_alfredo    S  12.75
7  ckn_alfredo_m   ckn_alfredo    M  16.75
8  ckn_alfredo_l   ckn_alfredo    L  20.75
9    ckn_pesto_s     ckn_pesto    S  12.75

In [7]:
# вся информация из таблиц
df = (
    df_order_details
    .merge(df_orders, on='order_id', how='left')
    .merge(df_pizzas, on='pizza_id', how='left')
    .merge(df_pizza_types, on='pizza_type_id', how='left')
)
df.head(10)

,order_details_id,order_id,pizza_id,quantity,date,time,pizza_type_id,size,price,name,category,ingredients
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,five_cheese,L,18.50,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go..."
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,ital_supr,L,20.75,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
4,5,2,mexicana_m,1,2015-01-01,11:57:40,mexicana,M,16.00,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
5,6,2,thai_ckn_l,1,2015-01-01,11:57:40,thai_ckn,L,20.75,The Thai Chicken Pizza,Chicken,"Chicken, Pineapple, Tomatoes, Red Peppers, Tha..."
6,7,3,ital_supr_m,1,2015-01-01,12:12:28,ital_supr,M,16.50,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
7,8,3,prsc_argla_l,1,2015-01-01,12:12:28,prsc_argla,L,20.75,The Prosciutto and Arugula Pizza,Supreme,"Prosciutto di San Daniele, Arugula, Mozzarella..."
8,9,4,ital_supr_m,1,2015-01-01,12:16:31,ital_supr,M,16.50,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
9,10,5,ital_supr_m,1,2015-01-01,12:21:30,ital_supr,M,16.50,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  str
 3   quantity          48620 non-null  int64
 4   date              48620 non-null  str
 5   time              48620 non-null  str
 6   pizza_type_id     48620 non-null  str
 7   size              48620 non-null  str
 8   price             48620 non-null  float64
 9   name              48620 non-null  str
 10  category          48620 non-null  str
 11  ingredients       48620 non-null  str
dtypes: float64(1), int64(3), str(8)
memory usage: 4.5 MB

In [9]:
df.shape

(48620, 12)

In [10]:
df.head()

,order_details_id,order_id,pizza_id,quantity,date,time,pizza_type_id,size,price,name,category,ingredients
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese"
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,five_cheese,L,18.50,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go..."
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,ital_supr,L,20.75,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
4,5,2,mexicana_m,1,2015-01-01,11:57:40,mexicana,M,16.00,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."

In [11]:
df.describe

<bound method NDFrame.describe of        order_details_id  order_id       pizza_id  quantity        date  \
0                     1         1     hawaiian_m         1  2015-01-01
1                     2         2  classic_dlx_m         1  2015-01-01
2                     3         2  five_cheese_l         1  2015-01-01
3                     4         2    ital_supr_l         1  2015-01-01
4                     5         2     mexicana_m         1  2015-01-01
...                 ...       ...            ...       ...         ...
48615             48616     21348  ckn_alfredo_m         1  2015-12-31
48616             48617     21348  four_cheese_l         1  2015-12-31
48617             48618     21348   napolitana_s         1  2015-12-31
48618             48619     21349     mexicana_l         1  2015-12-31
48619             48620     21350      bbq_ckn_s         1  2015-12-31

           time pizza_type_id size  price                        name  \
0      11:38:36      hawaiian    M  13.25          The Hawaiian Pizza
1      11:57:40   classic_dlx    M  16.00    The Classic Deluxe Pizza
2      11:57:40   five_cheese    L  18.50       The Five Cheese Pizza
3      11:57:40     ital_supr    L  20.75   The Italian Supreme Pizza
4      11:57:40      mexicana    M  16.00          The Mexicana Pizza
...         ...           ...  ...    ...                         ...
48615  21:23:10   ckn_alfredo    M  16.75   The Chicken Alfredo Pizza
48616  21:23:10   four_cheese    L  17.95       The Four Cheese Pizza
48617  21:23:10    napolitana    S  12.00        The Napolitana Pizza
48618  22:09:54      mexicana    L  20.25          The Mexicana Pizza
48619  23:02:05       bbq_ckn    S  12.75  The Barbecue Chicken Pizza

      category                                        ingredients
0      Classic           Sliced Ham, Pineapple, Mozzarella Cheese
1      Classic  Pepperoni, Mushrooms, Red Onions, Red Peppers,...
2       Veggie  Mozzarella Cheese, Provolone Cheese, Smoked Go...
3      Supreme  Calabrese Salami, Capocollo, Tomatoes, Red Oni...
4       Veggie  Tomatoes, Red Peppers, Jalapeno Peppers, Red O...
...        ...                                                ...
48615  Chicken  Chicken, Red Onions, Red Peppers, Mushrooms, A...
48616   Veggie  Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...
48617  Classic  Tomatoes, Anchovies, Green Olives, Red Onions,...
48618   Veggie  Tomatoes, Red Peppers, Jalapeno Peppers, Red O...
48619  Chicken  Barbecued Chicken, Red Peppers, Green Peppers,...

[48620 rows x 12 columns]>